# Generated by Django 3.1 on 2020-09-03 04:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogpage_postpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', default='Add you content here')), ('cardPost', wagtail.core.blocks.StructBlock([('author', wagtail.core.blocks.CharBlock(default='Add you content here', max_lengrth=100)), ('date_posted', wagtail.core.blocks.DateBlock())])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock())]))]),
        ),
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('Post', wagtail.core.blocks.StructBlock([('author', wagtail.core.blocks.CharBlock(default='Add your author here')), ('date_posted', wagtail.core.blocks.DateBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(default='Add your content here'))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock())])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(default='Add your content here'))]))]),
        ),
    ]
