# Generated by Django 3.1.1 on 2020-09-04 05:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200903_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('Post', wagtail.core.blocks.StructBlock([('author', wagtail.core.blocks.CharBlock(default='Add your author here')), ('date_posted', wagtail.core.blocks.DateBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock(default='контент сюда'))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock())])), ('text', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(default='Add your content here'))])), ('text2', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(default='Add your content here'))]))]),
        ),
    ]
